import clsx from "clsx";

export function cn(...inputs) {
  return clsx(inputs);
}

export const socialImageData = [
  {
    index: 1,
    icon: "/images/imo.png",
    link: "https://www.imo.com",
    name: "imo",
    checked: false,
  },
  {
    index: 2,
    icon: "/images/instagram.png",
    link: "https://www.instagram.com",
    name: "instagram",
    checked: false,
  },
  {
    index: 3,
    icon: "/images/link.png",
    link: "https://www.link.com",
    name: "link",
    checked: false,
  },
  {
    index: 4,
    icon: "/images/linkedin.png",
    link: "https://www.linkedin.com",
    name: "linkedin",
    checked: false,
  },
  {
    index: 5,
    icon: "/images/microsoft.png",
    link: "https://www.microsoft.com",
    name: "microsoft",
    checked: false,
  },
  {
    index: 6,
    icon: "/images/outlook.png",
    link: "https://www.outlook.com",
    name: "outlook",
    checked: false,
  },
  {
    index: 7,
    icon: "/images/paypal.png",
    link: "https://www.paypal.com",
    name: "paypal",
    checked: false,
  },
  {
    index: 8,
    icon: "/images/pinterest.png",
    link: "https://www.pinterest.com",
    name: "pinterest",
    checked: false,
  },
  {
    index: 9,
    icon: "/images/reddit.png",
    link: "https://www.reddit.com",
    name: "reddit",
    checked: false,
  },
  {
    index: 10,
    icon: "/images/shazam.png",
    link: "https://www.shazam.com",
    name: "shazam",
    checked: false,
  },
  {
    index: 11,
    icon: "/images/skype.png",
    link: "https://www.skype.com",
    name: "skype",
    checked: false,
  },
  {
    index: 12,
    icon: "/images/slack.png",
    link: "https://www.slack.com",
    name: "slack",
    checked: false,
  },
  {
    index: 13,
    icon: "/images/snapchat.png",
    link: "https://www.snapchat.com",
    name: "snapchat",
    checked: false,
  },
  {
    index: 14,
    icon: "/images/steam.png",
    link: "https://www.steam.com",
    name: "steam",
    checked: false,
  },
  {
    index: 15,
    icon: "/images/telegram.png",
    link: "https://www.telegram.com",
    name: "telegram",
    checked: false,
  },
  {
    index: 16,
    icon: "/images/tiktok.png",
    link: "https://www.tiktok.com",
    name: "tiktok",
    checked: false,
  },
  {
    index: 17,
    icon: "/images/twitter.png",
    link: "https://www.twitter.com",
    name: "twitter",
    checked: false,
  },
  {
    index: 18,
    icon: "/images/vimeo.png",
    link: "https://www.vimeo.com",
    name: "vimeo",
    checked: false,
  },
  {
    index: 19,
    icon: "/images/youtube.png",
    link: "https://www.youtube.com",
    name: "youtube",
    checked: false,
  },
];
